version: '3'
services:
  nodeserver:
    build:
      context: ./app
    container_name: nodeserver
    ports:
      - "5000:5000"

  nginx:
    build:
      context: ./nginx
    container_name: nginx
    restart: always
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - nodeserver
